### ISSUE TITLE
Fuses ATmega1284P-PU

### ISSUE THREAD

**Issue by vslinuxdotnet** [agn453/Z80-MBC2-master#1]
Hello,
What is the fuses to ATmega1284P-PU ?

Thanks 
VS

**Comment by agn453** [comment]
Sorry about the delay responding.

I've used the Arduino IDE on a Raspberry Pi with a USBasp programmer board to program my 1284P-PU.
Make sure you install the MightyCore Bootloader.

The settings I use are

Board: ATmega1284
Clock: External 20MHz   (I have installed a 20MHz crystal on my Z80-MBC2 - use 16MHz is that's what you have)
BOD: BOD 2.7V
Compiler LTO: Disabled
Variant: 1284P
Pinout: Standard
Bootloader: Yes (UART0)
Programmer: USBasp

If you need the actual fuse byte value then there are AVR fuse calculators on the net that you can search for.  Using the Arduino IDE works this out for itself based on the settings.

I hope this helps.
